vich_uploader:
    db_driver: orm

    mappings:
       horses:
           uri_prefix: /images/horses
           upload_destination: '%kernel.project_dir%/public/images/horses'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
           
    metadata:
        type: attribute
